assets:
  - name: kb_bucket
    type: s3
    uri: s3://panorama_with_bb-kb/
  - name: raw_bucket
    type: s3
    uri: s3://panorama_with_bb-raw/

glossary:
  - term: knowledge_base
    definition: Document corpus for retrieval augmented generation.
  - term: raw_zone
    definition: Landing zone for unprocessed data.

