name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install ruff mypy pytest
      - name: Lint
        run: |
          . .venv/bin/activate
          ruff check src || true
      - name: Type check
        run: |
          . .venv/bin/activate
          mypy src || true
      - name: Tests
        run: |
          . .venv/bin/activate
          pytest -q
