name: CD
on:
  workflow_dispatch:
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder deploy
        run: echo "Deploy would run SAM/CDK here"

