repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.120
    hooks:
      - id: checkov
        args: ["-d", ".", "--framework", "terraform", "--quiet"]
  - repo: https://github.com/aquasecurity/trivy
    rev: v0.53.0
    hooks:
      - id: trivy-iac
        args: ["--severity", "HIGH,CRITICAL", "--exit-code", "1", "."]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks: [{ id: ruff }, { id: ruff-format }]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks: [{ id: black }]
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.9
    hooks: [{ id: bandit }]
  - repo: local
    hooks:
      - id: ban-binaries
        name: ban-binaries
        entry: scripts/ban_binaries.sh
        language: system
        files: '.*'

