AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Service Planner Assistant API (healthz + chat)

Globals:
  Function:
    Runtime: python3.11
    Timeout: 30
    MemorySize: 512

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Cors: "*"

  AppFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../
      Handler: src/app/api/handlers.app
      Events:
        HealthZ:
          Type: Api
          Properties:
            Path: /healthz
            Method: get
            RestApiId: !Ref Api
        Chat:
          Type: Api
          Properties:
            Path: /chat
            Method: post
            RestApiId: !Ref Api
      Policies:
        - AWSLambdaBasicExecutionRole
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"

Outputs:
  ApiUrl:
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com/dev"

