name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup uv + Python
        uses: astral-sh/setup-uv@v3
        with:
          python-version: '3.11'
      - name: Sync dependencies (dev)
        run: |
          uv sync --group dev
      - name: Lint
        run: |
          uv run ruff check src || true
          uv run black --check src || true
      - name: Type check
        run: |
          uv run mypy src || true
      - name: Tests
        run: |
          uv run pytest -q
