tasks:
  rag:
    provider: bedrock
    model_id: anthropic.claude-3-5-sonnet-20240620-v1:0
    temperature: 0.2
    max_tokens: 1024
  classify:
    provider: bedrock
    model_id: meta.llama3-70b-instruct-v1:0
    temperature: 0.0
    max_tokens: 256
  embed:
    provider: bedrock
    model_id: amazon.titan-embed-text-v2:0

guardrails:
  standard: true

